### ISSUE TITLE
Add support for SameSite flags

### ISSUE THREAD

**Issue by fishouttah20** [AirisX/nginx_cookie_flag_module#1]
See details in the RFC: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00
and a nice write-up by @scotthelme  https://scotthelme.co.uk/tough-cookies/

Please also consider cookie prefixes: __Host and __Secure (see tough-cookies link)

**Comment by AirisX** [comment]
Thanks. I'll consider the options you specified.

**Comment by danlsgiga** [comment]
Definitely this is something I'm looking hard to have on Nginx side to protect the backend apps.
Does it actually look into all Set-Cookie headers? Since upstreams can send multiple Set-Cookie headers we need to make sure it is applied to all.

**Comment by AirisX** [comment]
Hi, @danlsgiga, 

yes, it does. If the token "*" is specified in the firs argument of the directive it will be applied to all cookies sent by the upstream.

**Comment by danlsgiga** [comment]
@AirisX thanks for the quick feedback!

Don't want to be a sucker making this question but, do you have any idea when you will be able to add the SameSite flag as well?

**Comment by AirisX** [comment]
Hi @danlsgiga,

Try the [feature/samesite_flag](https://github.com/AirisX/nginx_cookie_flag_module/tree/feature/samesite_flag)  branch

**Comment by danlsgiga** [comment]
Oh, awesome!! Will give it a try @AirisX.

Would be fair to say the new syntax would be:

**Comment by danlsgiga** [comment]
Never mind, I figured reading the code it should be samesite_lax or samesite_strict. Cool! Thanks a lot... will get back as soon as I get it going in my Dev environment.

**Comment by AirisX** [comment]
Yes, that's right. I'll fix the Readme after testing. @danlsgiga, waiting for your conclusion.
Thanks!

**Comment by danlsgiga** [comment]
Fantastic!! It works beautifully!
The syntax that worked was:

`set_cookie_flag * HttpOnly Secure SameSite=[Lax|Strict]`

Super duper awesome!

Thanks @AirisX!!

**Comment by danlsgiga** [comment]
Hi @AirisX, any plans on merging that to the master branch?

**Comment by AirisX** [comment]
Merged to the master branch.

**Comment by AirisX** [comment]
Added support for SameSite
