### ISSUE TITLE
memory deallocations

### ISSUE THREAD

**Issue by h0rs31** [AirisX/nginx_cookie_flag_module#2]
Hi,

I have a n00b question.

In lines where `ngx_pnalloc` is invoked (such as [here](https://github.com/AirisX/nginx_cookie_flag_module/blob/master/ngx_http_cookie_flag_filter_module.c#L250)), where/when is this allocated memory freed?

**Comment by AirisX** [comment]
Hi @h0rs31,

It is freed by nginx itself.
